"""creat goods shop store table

Revision ID: 0b295d3f2e47
Revises: 3613ad9f310c
Create Date: 2019-05-02 23:06:12.967643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b295d3f2e47'
down_revision = '3613ad9f310c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_basic',
    sa.Column('shop_basic_id', sa.Integer(), nullable=False),
    sa.Column('shop_basic_uuid', sa.String(length=128), nullable=True),
    sa.Column('shop_basic_type', sa.Integer(), nullable=True),
    sa.Column('shop_basic_name', sa.String(length=128), nullable=True),
    sa.Column('shop_basic_logo_url', sa.String(length=256), nullable=True),
    sa.Column('shop_basic_mobile_head_image_url', sa.String(length=256), nullable=True),
    sa.Column('shop_basis_createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shop_basic_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_shop_basic_shop_basic_uuid'), 'shop_basic', ['shop_basic_uuid'], unique=True)
    op.create_table('store_goods_classify',
    sa.Column('store_goods_classify_id', sa.Integer(), nullable=False),
    sa.Column('store_goods_classify_uuid', sa.String(length=128), nullable=True),
    sa.Column('store_goods_classify_puuid', sa.String(length=128), nullable=True),
    sa.Column('store_goods_classify_name', sa.String(length=128), nullable=True),
    sa.Column('store_goods_classify_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['store_goods_classify_puuid'], ['store_goods_classify.store_goods_classify_uuid'], ),
    sa.PrimaryKeyConstraint('store_goods_classify_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_store_goods_classify_store_goods_classify_uuid'), 'store_goods_classify', ['store_goods_classify_uuid'], unique=True)
    op.create_table('shop_goods_classify',
    sa.Column('shop_goods_classify_id', sa.Integer(), nullable=False),
    sa.Column('shop_goods_classify_uuid', sa.String(length=128), nullable=True),
    sa.Column('shop_goods_classify_puuid', sa.String(length=128), nullable=True),
    sa.Column('shop_goods_classify_name', sa.String(length=128), nullable=True),
    sa.Column('shop_basic_uuid', sa.String(length=128), nullable=True),
    sa.Column('shop_goods_classify_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['shop_basic_uuid'], ['shop_basic.shop_basic_uuid'], ),
    #sa.ForeignKeyConstraint(['shop_goods_classify_puuid'], ['shop_goods_classify.shop_goods_classify_uuid'], ),
    sa.PrimaryKeyConstraint('shop_goods_classify_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_shop_goods_classify_shop_goods_classify_uuid'), 'shop_goods_classify', ['shop_goods_classify_uuid'], unique=True)
    op.create_table('shop_user',
    sa.Column('shop_user_id', sa.Integer(), nullable=False),
    sa.Column('shop_basic_uuid', sa.String(length=128), nullable=True),
    sa.Column('ua_user_uuid', sa.String(length=128), nullable=True),
    sa.Column('shop_user_title', sa.String(length=64), nullable=True),
    sa.Column('shop_user_permission', sa.Integer(), nullable=True),
    sa.Column('shop_user_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['shop_basic_uuid'], ['shop_user.shop_basic_uuid'], ),
    #sa.ForeignKeyConstraint(['ua_user_uuid'], ['ua_users.ua_user_uuid'], ),
    sa.PrimaryKeyConstraint('shop_user_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_table('goods_basis',
    sa.Column('goods_basis_id', sa.Integer(), nullable=False),
    sa.Column('shop_goods_classify_uuid', sa.String(length=128), nullable=True),
    sa.Column('store_goods_classify_uuid', sa.String(length=128), nullable=True),
    sa.Column('shop_basic_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_title', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_type', sa.Integer(), nullable=True),
    sa.Column('goods_basis_updatetime', sa.DateTime(), nullable=True),
    sa.Column('goods_basis_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['shop_basic_uuid'], ['shop_basic.shop_basic_uuid'], ),
    #sa.ForeignKeyConstraint(['shop_goods_classify_uuid'], ['shop_goods_classify.shop_goods_classify_uuid'], ),
    #sa.ForeignKeyConstraint(['store_goods_classify_uuid'], ['store_goods_classify.store_goods_classify_uuid'], ),
    sa.PrimaryKeyConstraint('goods_basis_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_goods_basis_goods_basis_uuid'), 'goods_basis', ['goods_basis_uuid'], unique=True)
    op.create_table('goods_basis_description_mobile_client',
    sa.Column('goods_basis_description_mobile_client_id', sa.Integer(), nullable=False),
    sa.Column('goods_basis_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_description_mobile_client_html', mysql.LONGTEXT(), nullable=True),
    #sa.ForeignKeyConstraint(['goods_basis_uuid'], ['goods_basis.goods_basis_uuid'], ),
    sa.PrimaryKeyConstraint('goods_basis_description_mobile_client_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_table('goods_basis_dynamic_attributs',
    sa.Column('goods_basis_customize_attributs_id', sa.Integer(), nullable=False),
    sa.Column('goods_basis_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_customize_attributs_name', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_customize_attributs_value', sa.String(length=128), nullable=True),
    #sa.ForeignKeyConstraint(['goods_basis_uuid'], ['goods_basis.goods_basis_uuid'], ),
    sa.PrimaryKeyConstraint('goods_basis_customize_attributs_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_table('goods_basis_hotimage',
    sa.Column('goods_basis_hotimage_id', sa.Integer(), nullable=False),
    sa.Column('goods_basis_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_hotimage_url', sa.String(length=256), nullable=True),
    sa.Column('goods_basis_hotimage_sort', sa.Integer(), nullable=True),
    #sa.ForeignKeyConstraint(['goods_basis_uuid'], ['goods_basis.goods_basis_uuid'], ),
    sa.PrimaryKeyConstraint('goods_basis_hotimage_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_table('goods_basis_sales_data_classify',
    sa.Column('goods_basis_sales_data_classify_id', sa.Integer(), nullable=False),
    sa.Column('goods_basis_sales_data_classify_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_puuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_uuid', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_title', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_name', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_remark', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_image_url', sa.String(length=256), nullable=True),
    sa.Column('goods_basis_sales_data_classify_price', sa.Integer(), nullable=True),
    sa.Column('goods_basis_sales_data_classify_stock', sa.Integer(), nullable=True),
    sa.Column('goods_basis_sales_data_classify_shop_code', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_bar_code', sa.String(length=128), nullable=True),
    sa.Column('goods_basis_sales_data_classify_sort', sa.Integer(), nullable=True),
    #sa.ForeignKeyConstraint(['goods_basis_sales_data_classify_puuid'], ['goods_basis_sales_data_classify.goods_basis_sales_data_classify_uuid'], ),
    #sa.ForeignKeyConstraint(['goods_basis_uuid'], ['goods_basis.goods_basis_uuid'], ),
    sa.PrimaryKeyConstraint('goods_basis_sales_data_classify_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_goods_basis_sales_data_classify_goods_basis_sales_data_classify_uuid'), 'goods_basis_sales_data_classify', ['goods_basis_sales_data_classify_uuid'], unique=True)
    op.create_foreign_key(None, 'ua_session_data', 'ua_session_base', ['ua_sb_key'], ['ua_sb_key'])
    op.create_foreign_key(None, 'ua_users_account_detail', 'ua_users', ['ua_user_uuid'], ['ua_user_uuid'])
    op.create_foreign_key(None, 'ua_users_credit_detail', 'ua_users', ['ua_user_uuid'], ['ua_user_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ua_users_credit_detail', type_='foreignkey')
    #op.drop_constraint(None, 'ua_users_account_detail', type_='foreignkey')
    #op.drop_constraint(None, 'ua_session_data', type_='foreignkey')
    op.drop_index(op.f('ix_goods_basis_sales_data_classify_goods_basis_sales_data_classify_uuid'), table_name='goods_basis_sales_data_classify')
    op.drop_table('goods_basis_sales_data_classify')
    op.drop_table('goods_basis_hotimage')
    op.drop_table('goods_basis_dynamic_attributs')
    op.drop_table('goods_basis_description_mobile_client')
    op.drop_index(op.f('ix_goods_basis_goods_basis_uuid'), table_name='goods_basis')
    op.drop_table('goods_basis')
    op.drop_table('shop_user')
    op.drop_index(op.f('ix_shop_goods_classify_shop_goods_classify_uuid'), table_name='shop_goods_classify')
    op.drop_table('shop_goods_classify')
    op.drop_index(op.f('ix_store_goods_classify_store_goods_classify_uuid'), table_name='store_goods_classify')
    op.drop_table('store_goods_classify')
    op.drop_index(op.f('ix_shop_basic_shop_basic_uuid'), table_name='shop_basic')
    op.drop_table('shop_basic')
    # ### end Alembic commands ###
