"""add user status in ua_user table

Revision ID: 2ace1f254c4e
Revises: 0b295d3f2e47
Create Date: 2019-05-03 01:43:06.448456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ace1f254c4e'
down_revision = '0b295d3f2e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.create_foreign_key(None, 'goods_basis', 'shop_basic', ['shop_basic_uuid'], ['shop_basic_uuid'])
    op.create_foreign_key(None, 'goods_basis', 'store_goods_classify', ['store_goods_classify_uuid'], ['store_goods_classify_uuid'])
    op.create_foreign_key(None, 'goods_basis', 'shop_goods_classify', ['shop_goods_classify_uuid'], ['shop_goods_classify_uuid'])
    op.create_foreign_key(None, 'goods_basis_description_mobile_client', 'goods_basis', ['goods_basis_uuid'], ['goods_basis_uuid'])
    op.create_foreign_key(None, 'goods_basis_dynamic_attributs', 'goods_basis', ['goods_basis_uuid'], ['goods_basis_uuid'])
    op.create_foreign_key(None, 'goods_basis_hotimage', 'goods_basis', ['goods_basis_uuid'], ['goods_basis_uuid'])
    op.create_foreign_key(None, 'goods_basis_sales_data_classify', 'goods_basis_sales_data_classify', ['goods_basis_sales_data_classify_puuid'], ['goods_basis_sales_data_classify_uuid'])
    op.create_foreign_key(None, 'goods_basis_sales_data_classify', 'goods_basis', ['goods_basis_uuid'], ['goods_basis_uuid'])
    op.create_foreign_key(None, 'shop_goods_classify', 'shop_basic', ['shop_basic_uuid'], ['shop_basic_uuid'])
    op.create_foreign_key(None, 'shop_goods_classify', 'shop_goods_classify', ['shop_goods_classify_puuid'], ['shop_goods_classify_uuid'])
    op.create_foreign_key(None, 'shop_user', 'ua_users', ['ua_user_uuid'], ['ua_user_uuid'])
    op.create_foreign_key(None, 'shop_user', 'shop_basic', ['shop_basic_uuid'], ['shop_basic_uuid'])
    op.create_foreign_key(None, 'store_goods_classify', 'store_goods_classify', ['store_goods_classify_puuid'], ['store_goods_classify_uuid'])
    op.create_foreign_key(None, 'ua_session_data', 'ua_session_base', ['ua_sb_key'], ['ua_sb_key'])
    op.create_foreign_key(None, 'ua_users_account_detail', 'ua_users', ['ua_user_uuid'], ['ua_user_uuid'])
    op.create_foreign_key(None, 'ua_users_credit_detail', 'ua_users', ['ua_user_uuid'], ['ua_user_uuid'])
    '''
    op.add_column('ua_users', sa.Column('ua_user_status', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.drop_constraint(None, 'ua_users_credit_detail', type_='foreignkey')
    op.drop_constraint(None, 'ua_users_account_detail', type_='foreignkey')
    op.drop_constraint(None, 'ua_session_data', type_='foreignkey')
    op.drop_constraint(None, 'store_goods_classify', type_='foreignkey')
    op.drop_constraint(None, 'shop_user', type_='foreignkey')
    op.drop_constraint(None, 'shop_user', type_='foreignkey')
    op.drop_constraint(None, 'shop_goods_classify', type_='foreignkey')
    op.drop_constraint(None, 'shop_goods_classify', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis_sales_data_classify', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis_sales_data_classify', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis_hotimage', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis_dynamic_attributs', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis_description_mobile_client', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis', type_='foreignkey')
    op.drop_constraint(None, 'goods_basis', type_='foreignkey')
    '''

    op.drop_column('ua_users', 'ua_user_status')
    # ### end Alembic commands ###
