"""add user account table

Revision ID: 3613ad9f310c
Revises: 74548eed85a8
Create Date: 2019-05-02 22:44:11.654485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3613ad9f310c'
down_revision = '74548eed85a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ua_users_account_detail',
    sa.Column('ua_user_account_detail_id', sa.Integer(), nullable=False),
    sa.Column('ua_user_uuid', sa.String(length=128), nullable=True),
    sa.Column('ua_user_account_detail_log', sa.String(length=256), nullable=True),
    sa.Column('ua_user_account_detail_classify', sa.Integer(), nullable=True),
    sa.Column('ua_user_account_detail_pay', sa.Integer(), nullable=True),
    sa.Column('ua_user_account_detail_val', sa.Integer(), nullable=True),
    sa.Column('ua_user_account_detail_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['ua_user_uuid'], ['ua_users.ua_user_uuid'], ),
    sa.PrimaryKeyConstraint('ua_user_account_detail_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_ua_users_account_detail_ua_user_account_detail_classify'), 'ua_users_account_detail', ['ua_user_account_detail_classify'], unique=False)
    op.create_table('ua_users_credit_detail',
    sa.Column('ua_user_credit_detail_id', sa.Integer(), nullable=False),
    sa.Column('ua_user_uuid', sa.String(length=128), nullable=True),
    sa.Column('ua_user_credit_detail_log', sa.String(length=256), nullable=True),
    sa.Column('ua_user_credit_detail_signal', sa.Integer(), nullable=True),
    sa.Column('ua_user_credit_detail_val', sa.Integer(), nullable=True),
    sa.Column('ua_user_credit_detail_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['ua_user_uuid'], ['ua_users.ua_user_uuid'], ),
    sa.PrimaryKeyConstraint('ua_user_credit_detail_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_ua_users_credit_detail_ua_user_credit_detail_signal'), 'ua_users_credit_detail', ['ua_user_credit_detail_signal'], unique=False)
    op.create_foreign_key(None, 'ua_session_data', 'ua_session_base', ['ua_sb_key'], ['ua_sb_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ua_session_data', type_='foreignkey')
    op.drop_index(op.f('ix_ua_users_credit_detail_ua_user_credit_detail_signal'), table_name='ua_users_credit_detail')
    op.drop_table('ua_users_credit_detail')
    op.drop_index(op.f('ix_ua_users_account_detail_ua_user_account_detail_classify'), table_name='ua_users_account_detail')
    op.drop_table('ua_users_account_detail')
    # ### end Alembic commands ###
