"""update shop basic add shop status

Revision ID: 56c8446e4a07
Revises: 87db50dbacff
Create Date: 2019-06-04 03:03:53.945719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c8446e4a07'
down_revision = '87db50dbacff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_basic', sa.Column('shop_basic_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_basic', 'shop_basic_status')
    # ### end Alembic commands ###
