"""add users table

Revision ID: 74548eed85a8
Revises: 
Create Date: 2019-02-22 01:30:29.638245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74548eed85a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ua_session_base',
    sa.Column('ua_sb_key', sa.String(length=256), nullable=False),
    sa.Column('ua_sb_ip', sa.String(length=128), nullable=True),
    sa.Column('user_uuid', sa.String(length=128), nullable=True),
    sa.Column('ua_sb_exceed', sa.SmallInteger(), nullable=True),
    sa.Column('ua_sb_lastheart', sa.BigInteger(), nullable=True),
    sa.Column('ua_sb_createtime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('ua_sb_key'),
    mysql_ENGINE='MEMORY'
    )
    op.create_table('ua_users',
    sa.Column('ua_user_id', sa.Integer(), nullable=False),
    sa.Column('ua_user_uuid', sa.String(length=128), nullable=True),
    sa.Column('ua_user_system_role', sa.Integer(), nullable=True),
    sa.Column('ua_user_email', sa.String(length=128), nullable=True),
    sa.Column('ua_user_moblie', sa.String(length=64), nullable=True),
    sa.Column('ua_user_nick', sa.String(length=64), nullable=True),
    sa.Column('ua_user_headimg', sa.String(length=256), nullable=True),
    sa.Column('ua_pwd_hash', sa.String(length=128), nullable=True),
    sa.Column('ua_email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('ua_mobile_confirmed', sa.Boolean(), nullable=True),
    sa.Column('ua_createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ua_user_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_ua_users_ua_user_email'), 'ua_users', ['ua_user_email'], unique=True)
    op.create_index(op.f('ix_ua_users_ua_user_moblie'), 'ua_users', ['ua_user_moblie'], unique=True)
    op.create_index(op.f('ix_ua_users_ua_user_nick'), 'ua_users', ['ua_user_nick'], unique=True)
    op.create_index(op.f('ix_ua_users_ua_user_uuid'), 'ua_users', ['ua_user_uuid'], unique=True)
    op.create_table('ua_session_data',
    sa.Column('ua_sb_key', sa.String(length=128), nullable=False),
    sa.Column('ua_sd_key', sa.String(length=64), nullable=False),
    sa.Column('ua_sd_value', sa.VARBINARY(length=512), nullable=True),
    sa.Column('ua_sd_type', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['ua_sb_key'], ['ua_session_base.ua_sb_key'], ),
    sa.PrimaryKeyConstraint('ua_sb_key', 'ua_sd_key'),
    mysql_ENGINE='MEMORY'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ua_session_data')
    op.drop_index(op.f('ix_ua_users_ua_user_uuid'), table_name='ua_users')
    op.drop_index(op.f('ix_ua_users_ua_user_nick'), table_name='ua_users')
    op.drop_index(op.f('ix_ua_users_ua_user_moblie'), table_name='ua_users')
    op.drop_index(op.f('ix_ua_users_ua_user_email'), table_name='ua_users')
    op.drop_table('ua_users')
    op.drop_table('ua_session_base')
    # ### end Alembic commands ###
