"""update shop basic add owned user

Revision ID: 87db50dbacff
Revises: bf672b063071
Create Date: 2019-06-04 02:50:14.045644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87db50dbacff'
down_revision = 'bf672b063071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_basic', sa.Column('shop_owned_user_uuid', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_basic', 'shop_owned_user_uuid')
    # ### end Alembic commands ###
