"""add uuid seed data table

Revision ID: bf672b063071
Revises: e046c8cff472
Create Date: 2019-06-04 00:24:38.423151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf672b063071'
down_revision = 'e046c8cff472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_uuid_seeds',
    sa.Column('utility_uuid_seed_id', sa.Integer(), nullable=False),
    sa.Column('utility_uuid_seed_value', sa.String(length=64), nullable=True),
    sa.Column('utility_uuid_seed_createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('utility_uuid_seed_id'),
    mysql_ENGINE='MyISAM'
    )
    op.create_index(op.f('ix_utility_uuid_seeds_utility_uuid_seed_value'), 'utility_uuid_seeds', ['utility_uuid_seed_value'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_uuid_seeds_utility_uuid_seed_value'), table_name='utility_uuid_seeds')
    op.drop_table('utility_uuid_seeds')
    # ### end Alembic commands ###
