"""delete usernick uni

Revision ID: e046c8cff472
Revises: 2ace1f254c4e
Create Date: 2019-05-18 05:16:21.409936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e046c8cff472'
down_revision = '2ace1f254c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ua_users_ua_user_nick', table_name='ua_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ua_users_ua_user_nick', 'ua_users', ['ua_user_nick'], unique=True)
    # ### end Alembic commands ###
